name: Order Scheduler

on:
  schedule:
    # Runs every 5 minutes
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  trigger-scheduler:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Scheduler API
        run: |
          curl --fail \
            --request POST \
            --header "x-secret-key: ${{ secrets.SCHEDULER_SECRET }}" \
            "${{ secrets.SCHEDULER_URL }}"
